const monsters=[
{name:'苔冠幽狼',latin:'Lupus sylvae',type:'森',color:'#9ac99c',habitat:'暮霧森林',risk:2,pos:'0% 0%',summary:'頭戴活苔與枝角的森林守望者，能聽見樹根間的低語。',body:'苔冠幽狼不以血肉為主食，而是汲取林間逸散的生命魔力。牠額上的枝角每逢春季開出細白小花，是森林健康的徵兆。',ability:'根網感知：透過腳下的菌絲追蹤數里之外的動靜。苔霧庇護：呼出綠色薄霧，隱藏自己與幼獸的足跡。',note:'避免折斷活枝。將掉落的橡實放在路旁，牠通常會容許旅人通行。'},
{name:'燼翼螈龍',latin:'Draco favillae',type:'炎',color:'#f0a477',habitat:'赤脊火山',risk:4,pos:'50% 0%',summary:'翅膜流淌熔火的螈龍，休眠時像一塊尚未冷卻的岩石。',body:'燼翼螈龍將火山玻璃吞入腹中，以其研磨礦物。翅膀上的亮紋隨體溫改變；深紅代表平靜，近乎白色則是即將噴焰的訊號。',ability:'熔息：噴出黏稠高熱的火流。燼翼震擊：鼓翼揚起熾熱灰燼，遮蔽敵人的視線。',note:'保持上風位置。發現翅紋轉白時，立即退至岩壁後方，切勿靠近巢穴。'},
{name:'霜鏡靈鴞',latin:'Strix glacialis',type:'霜',color:'#acd9ee',habitat:'銀眠雪原',risk:1,pos:'100% 0%',summary:'羽翼宛如薄冰，在極光下能映出尚未發生的短暫片段。',body:'霜鏡靈鴞的身體半透明，月光可以穿過羽毛。牠常停棲於凍湖中央，長久注視水面，直到冰下的微光消失。',ability:'冰鏡幻影：留下折射月光的殘像。寒息：將水汽凝成冰晶，干擾追逐者的方向感。',note:'以遠距觀察為主。不要用火把直照牠的眼睛，溫和的魔物也可能因驚嚇引發暴雪。'},
{name:'暮影夢豹',latin:'Panthera umbrae',type:'影',color:'#c4a2ee',habitat:'無月幽谷',risk:4,pos:'0% 100%',summary:'游走於夢境邊界的獵手，尾端的紫色光霧會讓人忘記來路。',body:'暮影夢豹在日落後才留下實體足跡。牠偏愛寂靜與恐懼，能察覺旅人反覆出現的夢，並以熟悉的聲音引誘獵物離開營地。',ability:'影步：在相連的陰影間短距移動。夢囈：模仿記憶中的聲音，削弱獵物的判斷。',note:'同行者應事先約定口令。若聽見營地外有人呼喚姓名，先確認夥伴的位置。'},
{name:'潮紋玄甲',latin:'Testudo pelagica',type:'潮',color:'#7ed6ce',habitat:'沉星海灣',risk:2,pos:'50% 100%',summary:'背甲刻有古老潮紋的巨龜，月圓之夜會引導迷航船隻。',body:'潮紋玄甲背負的紋路並非天然花紋，而是隨年歲累積的魔力結晶。漁民相信，每一道發光的紋路，都記錄著牠曾經走過的一條海流。',ability:'潮流牽引：改變周圍水流，推離船隻或敵人。玄甲屏障：展開淡藍色水幕，抵擋衝擊。',note:'不可敲擊背甲或刮取結晶。跟隨牠航行時，保持至少兩個船身的距離。'},
{name:'雷羽獅鷲',latin:'Gryphus fulgur',type:'雷',color:'#e6cb7b',habitat:'風鳴高峰',risk:3,pos:'100% 100%',summary:'金色羽端蓄積雷光，在暴風雨中巡守高山與天空的疆界。',body:'雷羽獅鷲會在風暴來臨前攀上最高的岩柱。牠用羽毛收集空中的電荷，成年個體展翅時，細小雷光會在羽端連成金色弧線。',ability:'雷羽散射：射出帶電的羽毛。風暴俯衝：借強風加速，以雷鳴般的衝擊驅逐入侵者。',note:'收起外露的金屬器具。若牠連續鳴叫三次，代表你已進入領地，應沿原路下山。'}];
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),filters=document.querySelector('#filters'),dialog=document.querySelector('#detail');let selected='全部';
for(const type of ['全部','森','炎','霜','影','潮','雷']){const b=document.createElement('button');b.textContent=type;b.type='button';b.setAttribute('aria-pressed',type===selected);b.onclick=()=>{selected=type;for(const child of filters.children)child.setAttribute('aria-pressed',child===b);render()};filters.append(b)}
function render(){const q=search.value.trim().toLowerCase();const shown=monsters.filter(m=>(selected==='全部'||m.type===selected)&&[m.name,m.latin,m.habitat,m.summary,m.ability].join(' ').toLowerCase().includes(q));grid.innerHTML='';shown.forEach(m=>{const i=monsters.indexOf(m);const card=document.createElement('button');card.className='card';card.style.setProperty('--pos',m.pos);card.style.setProperty('--accent',m.color);card.setAttribute('aria-label',`查看${m.name}詳細資料`);card.innerHTML=`<div class="art"><span class="serial">NO. ${String(i+1).padStart(3,'0')}</span></div><div class="card-body"><div class="row"><h3>${m.name}</h3><span class="tag">${m.type}屬性</span></div><p class="latin">${m.latin}</p><p class="summary">${m.summary}</p><div class="meta"><span>${m.habitat}</span><span class="risk">危險 ${'◆'.repeat(m.risk)}${'◇'.repeat(5-m.risk)}</span></div></div>`;card.onclick=()=>openDetail(m);grid.append(card)});document.querySelector('#count').textContent=`${shown.length} / ${monsters.length} 種`;document.querySelector('#empty').hidden=shown.length>0}
function openDetail(m){document.querySelector('#detail-body').innerHTML=`<div class="art detail-art" style="--pos:${m.pos}" role="img" aria-label="${m.name}魔物插畫"></div><div class="detail-copy"><p class="eyebrow">FIELD OBSERVATION</p><h2 id="detail-title">${m.name}</h2><p class="latin">${m.latin}</p><dl class="facts"><div><dt>屬性</dt><dd>${m.type}</dd></div><div><dt>棲地</dt><dd>${m.habitat}</dd></div><div><dt>危險程度</dt><dd>${m.risk} / 5</dd></div><div><dt>活動紀錄</dt><dd>霧境觀察卷 01</dd></div></dl><p>${m.body}</p><h3>特殊能力</h3><p>${m.ability}</p><h3>野外觀察筆記</h3><p>${m.note}</p></div>`;dialog.showModal()}
search.addEventListener('input',render);document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});render();
